#!/usr/bin/env bash
# export-to-claude.sh - generate a native Claude Code setup from kiro-rails Kiro files.
#
# Single source of truth = .kiro/*. Re-run after changing steering/hooks/agents/prompts/skills.
# Produces .claude/{CLAUDE.md, settings.json, hooks/guard-bash.sh, agents/, commands/, skills/}.
#
# Requires jq. See docs/references/kiro-to-claude-compatibility-2026-06-05.md
set -uo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

STEER=".kiro/steering"; HOOKS=".kiro/hooks"; AGENTS=".kiro/agents"; PROMPTS=".kiro/prompts"; SKILLS=".kiro/skills"
OUT="${1:-.claude}"

command -v jq >/dev/null 2>&1 || { echo "Error: jq is required for export-to-claude.sh"; exit 1; }
[ -d "$STEER" ] || { echo "Error: $STEER not found. Run from a kiro-rails project root."; exit 1; }

rm -rf "$OUT/agents" "$OUT/commands" "$OUT/skills"
mkdir -p "$OUT/hooks" "$OUT/agents" "$OUT/commands"

# ── 1) CLAUDE.md: steering concatenation (overrides first) ─────────────────────
{
  echo "# Project Rules (generated from kiro-rails steering by scripts/export-to-claude.sh)"
  echo "# Source of truth: .kiro/steering/*.md - edit there and re-run; do not edit this file."
  echo
  if [ -f "$STEER/user-project-overrides.md" ]; then cat "$STEER/user-project-overrides.md"; printf '\n\n---\n\n'; fi
  for f in $(find "$STEER" -name '*.md' -not -name 'user-project-overrides.md' | sort); do
    cat "$f"; printf '\n\n---\n\n'
  done
} > "$OUT/CLAUDE.md"

# ── 2) PreToolUse guard script ─────────────────────────────────────────────────
cp scripts/claude-guard-bash.sh "$OUT/hooks/guard-bash.sh"
chmod +x "$OUT/hooks/guard-bash.sh"

# ── 3) commands from prompts ───────────────────────────────────────────────────
for f in "$PROMPTS"/*.md; do
  [ -e "$f" ] || continue
  name=$(basename "$f" .md)
  desc=$(grep -m1 -E '.' "$f" | sed 's/^#\+ *//' | cut -c1-120)
  { printf -- '---\ndescription: "%s"\n---\n\n' "${desc//\"/\'}"; cat "$f"; } > "$OUT/commands/$name.md"
done

# ── 4) agents from .kiro/agents/*.json ─────────────────────────────────────────
map_tool() { case "$1" in
  read) echo Read;; write) echo Write;; edit) echo Edit;;
  grep) echo Grep;; glob) echo Glob;; shell) echo Bash;; *) echo "";; esac; }
for f in "$AGENTS"/*.json; do
  [ -e "$f" ] || continue
  name=$(jq -r '.name' "$f"); desc=$(jq -r '.description' "$f")
  ctools=""
  for t in $(jq -r '(.allowedTools // .tools // [])[]' "$f"); do
    m=$(map_tool "$t"); [ -n "$m" ] && ctools+="${ctools:+, }$m"
  done
  ref=$(jq -r '.prompt // ""' "$f"); body=""
  case "$ref" in
    file://*) p="$AGENTS/${ref#file://}"; [ -f "$p" ] && body=$(cat "$p") ;;
    "") ;; *) body="$ref" ;;
  esac
  { printf -- '---\nname: %s\ndescription: "%s"\n' "$name" "${desc//\"/\'}"
    [ -n "$ctools" ] && printf 'tools: %s\n' "$ctools"
    printf -- '---\n\n%s\n' "$body"; } > "$OUT/agents/$name.md"
done

# ── 5) skills (format compatible - copy) ───────────────────────────────────────
[ -d "$SKILLS" ] && cp -r "$SKILLS" "$OUT/skills"

# ── 6) settings.json: translate hooks + add PreToolUse guard + permissions ─────
# Build a JSON array of {type:"command", command:<arg>} from command strings (safe via --arg).
to_entries() {
  local out='[]' c
  for c in "$@"; do
    [ -z "$c" ] && continue
    out=$(jq -c --arg c "$c" '. + [{type:"command", command:$c}]' <<<"$out")
  done
  printf '%s' "$out"
}

ups=(); post=(); stop=(); skipped=()
for h in "$HOOKS"/*.kiro.hook; do
  [ -e "$h" ] || continue
  if ! jq empty "$h" 2>/dev/null; then skipped+=("$(basename "$h")"); continue; fi
  [ "$(jq -r '.enabled' "$h")" = "false" ] && continue
  cmd=$(jq -r '.then.command // ""' "$h"); [ -z "$cmd" ] && continue
  case "$(jq -r '.when.type' "$h")" in
    userPromptSubmit)            ups+=("$cmd") ;;
    fileEdit|fileEdited|fileSave|postToolUse) post+=("$cmd") ;;
    agentStop|stop)              stop+=("$cmd") ;;
    *) : ;;  # preCommit/manual: no clean Claude event - see compatibility doc
  esac
done

ups_json=$(to_entries "${ups[@]:-}")
post_json=$(to_entries "${post[@]:-}")
stop_json=$(to_entries "${stop[@]:-}")

jq -n --argjson ups "$ups_json" --argjson post "$post_json" --argjson stop "$stop_json" '
{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  hooks: (
    {}
    + (if ($ups|length)  > 0 then {UserPromptSubmit: [ {hooks: $ups} ]} else {} end)
    + {PreToolUse: [ {matcher: "Bash", hooks: [ {type: "command", command: "bash .claude/hooks/guard-bash.sh"} ]} ]}
    + (if ($post|length) > 0 then {PostToolUse: [ {matcher: "Edit|Write|MultiEdit", hooks: $post} ]} else {} end)
    + (if ($stop|length) > 0 then {Stop: [ {hooks: $stop} ]} else {} end)
  )
}' > "$OUT/settings.json"

echo "Generated $OUT/ : CLAUDE.md, settings.json, hooks/guard-bash.sh, $(ls "$OUT/agents" | wc -l | tr -d ' ') agents, $(ls "$OUT/commands" | wc -l | tr -d ' ') commands, $([ -d "$OUT/skills" ] && ls "$OUT/skills" | wc -l | tr -d ' ' || echo 0) skills."
if [ "${#skipped[@]}" -gt 0 ]; then
  echo "  Note: ${#skipped[@]} hook(s) skipped (not valid JSON, not translated): ${skipped[*]}" >&2
  echo "  See docs/references/kiro-to-claude-compatibility-2026-06-05.md" >&2
fi
