#!/usr/bin/env bash
# scripts/test-file-scaffold.sh — Auto-create matching test file for new source files
#
# When a new source file is created, this script generates the corresponding
# test file at the correct path with correct imports and skeleton.
#
# Follows naming-conventions.md:
#   Python: src/services/auth.py → tests/unit/test_auth.py
#   TypeScript: src/features/auth/auth.service.ts → tests/unit/auth.service.test.ts
#
# Zero dependencies beyond bash. Uses scripts/lib/template.sh for generation.
#
# Usage: test-file-scaffold.sh <source-file-path>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/template.sh"

# ──────────────────────────────────────────────
# Configuration
# ──────────────────────────────────────────────

# Directories that should NOT get test files (config, migrations, etc.)
SKIP_PATTERNS=(
    "tests/*"
    "*/tests/*"
    "*/migrations/*"
    "*/node_modules/*"
    "*/__pycache__/*"
    "*/dist/*"
    "*/build/*"
    "*/.venv/*"
    "*/.kiro/*"
    "*/docs/*"
    "scripts/*"
    "*/scripts/*"
    "*/conftest.py"
    "*/__init__.py"
    "*/setup.py"
    "*/manage.py"
)

# ──────────────────────────────────────────────
# Main logic
# ──────────────────────────────────────────────

main() {
    local source_file="${1:-}"

    if [ -z "$source_file" ]; then
        echo "test-file-scaffold: ERROR — requires a source file path"
        echo "Usage: test-file-scaffold.sh <source-file>"
        exit 1
    fi

    # Skip if file doesn't exist (deleted)
    [ -f "$source_file" ] || exit 0

    # Skip patterns (config, migrations, tests themselves, etc.)
    for pattern in "${SKIP_PATTERNS[@]}"; do
        if [[ "$source_file" == $pattern ]]; then
            exit 0
        fi
    done

    # Determine language and generate test path
    local ext="${source_file##*.}"
    local test_file=""
    local test_content=""

    case "$ext" in
        py)
            test_file=$(python_test_path "$source_file")
            test_content=$(python_test_content "$source_file" "$test_file")
            ;;
        ts|tsx)
            test_file=$(typescript_test_path "$source_file")
            test_content=$(typescript_test_content "$source_file" "$test_file")
            ;;
        js|jsx)
            test_file=$(javascript_test_path "$source_file")
            test_content=$(typescript_test_content "$source_file" "$test_file")
            ;;
        *)
            # Unsupported language — silent exit
            exit 0
            ;;
    esac

    # Skip if test file already exists
    if [ -f "$test_file" ]; then
        exit 0
    fi

    # Create directory if needed
    mkdir -p "$(dirname "$test_file")"

    # Write the test file
    echo "$test_content" > "$test_file"

    echo "test-file-scaffold: Created ${test_file} (for ${source_file})"
}

# ──────────────────────────────────────────────
# Python: path mapping + content generation
# ──────────────────────────────────────────────

python_test_path() {
    local source="$1"
    local filename
    filename=$(basename "$source" .py)

    # Determine test subdirectory from source path
    # backend/src/services/auth.py → tests/unit/services/test_auth.py
    # src/models/user.py → tests/unit/models/test_user.py
    local rel_dir
    rel_dir=$(dirname "$source" | sed -E 's|^(backend/)?src/||')

    # If the path doesn't have src/, put test next to a flat tests/unit/
    if [[ "$rel_dir" == "$source" ]] || [[ "$rel_dir" == "." ]]; then
        rel_dir=""
    fi

    if [ -n "$rel_dir" ]; then
        echo "tests/unit/${rel_dir}/test_${filename}.py"
    else
        echo "tests/unit/test_${filename}.py"
    fi
}

python_test_content() {
    local source="$1"
    local test_file="$2"
    local filename
    filename=$(basename "$source" .py)

    # Extract module name for import (convert path to dotted module)
    local module_path
    module_path=$(echo "$source" | sed -E 's|^(backend/)?||; s|/|.|g; s|\.py$||')

    # Extract class and function names from the source file
    local classes functions
    classes=$(grep -oE '^\s*class\s+([A-Za-z_][A-Za-z0-9_]*)' "$source" 2>/dev/null | sed -E 's/.*class\s+//' | head -5 || true)
    functions=$(grep -oE '^\s*def\s+([A-Za-z_][A-Za-z0-9_]*)' "$source" 2>/dev/null | sed -E 's/.*def\s+//; /^__/d' | head -5 || true)

    cat << EOF
"""
Tests for ${filename} module.

Source: ${source}
Auto-generated by test-file-scaffold. Add test cases below.
"""
import pytest

from ${module_path} import (
    # TODO: import the functions/classes you want to test
)


EOF

    # Generate test class if classes found
    if [ -n "$classes" ]; then
        while IFS= read -r cls; do
            [ -z "$cls" ] && continue
            cat << EOF
class Test${cls}:
    """Tests for ${cls}."""

    def test_${cls,,}_exists(self):
        """Verify ${cls} can be instantiated."""
        # TODO: implement
        pass


EOF
        done <<< "$classes"
    fi

    # Generate test functions if functions found
    if [ -n "$functions" ]; then
        while IFS= read -r func; do
            [ -z "$func" ] && continue
            cat << EOF
def test_${func}():
    """Test ${func} basic behavior."""
    # TODO: implement
    pass

EOF
        done <<< "$functions"
    fi

    # Fallback if nothing detected
    if [ -z "$classes" ] && [ -z "$functions" ]; then
        cat << EOF
def test_placeholder():
    """Placeholder — add real tests for ${filename}."""
    # TODO: implement tests
    pass
EOF
    fi
}

# ──────────────────────────────────────────────
# TypeScript: path mapping + content generation
# ──────────────────────────────────────────────

typescript_test_path() {
    local source="$1"
    local filename
    filename=$(basename "$source")
    local name_without_ext="${filename%.*}"
    local ext="${filename##*.}"

    # Determine test subdirectory
    # src/features/auth/auth.service.ts → tests/unit/auth/auth.service.test.ts
    local rel_dir
    rel_dir=$(dirname "$source" | sed -E 's|^(frontend/)?src/(features/)?||')

    if [[ "$rel_dir" == "$source" ]] || [[ "$rel_dir" == "." ]]; then
        rel_dir=""
    fi

    local test_ext="test.${ext}"

    if [ -n "$rel_dir" ]; then
        echo "tests/unit/${rel_dir}/${name_without_ext}.${test_ext}"
    else
        echo "tests/unit/${name_without_ext}.${test_ext}"
    fi
}

javascript_test_path() {
    typescript_test_path "$1"
}

typescript_test_content() {
    local source="$1"
    local test_file="$2"
    local filename
    filename=$(basename "$source")
    local name_without_ext="${filename%.*}"

    # Extract exported names from the source
    local exports
    exports=$(grep -oE 'export\s+(const|function|class|interface|type|enum)\s+([A-Za-z_][A-Za-z0-9_]*)' "$source" 2>/dev/null | sed -E 's/export\s+(const|function|class|interface|type|enum)\s+//' | head -5 || true)

    # Calculate relative import path from test file to source
    local source_abs test_dir
    source_abs=$(realpath "$source" 2>/dev/null || echo "$source")
    test_dir=$(dirname "$test_file")

    # Use @/ alias (per import-path-rules.md)
    local import_path
    import_path=$(echo "$source" | sed -E 's|^(frontend/)?src/|@/|; s|\.[^.]+$||')

    cat << EOF
/**
 * Tests for ${name_without_ext} module.
 *
 * Source: ${source}
 * Auto-generated by test-file-scaffold. Add test cases below.
 */
import { describe, it, expect } from 'vitest';

// TODO: import from source
// import { } from '${import_path}';

describe('${name_without_ext}', () => {
EOF

    # Generate test cases for exports
    if [ -n "$exports" ]; then
        while IFS= read -r exp; do
            [ -z "$exp" ] && continue
            cat << EOF
  describe('${exp}', () => {
    it('should exist', () => {
      // TODO: implement
      expect(true).toBe(true);
    });
  });

EOF
        done <<< "$exports"
    else
        cat << EOF
  it('should work', () => {
    // TODO: implement tests
    expect(true).toBe(true);
  });
EOF
    fi

    echo "});"
}

main "$@"
